//LOCALHOST
###
GET http://localhost:8080/contacts
###
GET http://localhost:8080/contacts/6268b3327cbe1abba92df8a6
###
GET http://localhost:8080/contacts/6268b3327cbe1abba92df8a7
###
GET http://localhost:8080/contacts/6268b3327cbe1abba92df8a8
###
POST http://localhost:8080/contacts/ HTTP/1.1 content-type: application/json

    {
    "firstName": "Joey",
    "lastName": "Tribbiani",
    "email": "JoeyDoesntShareFood@FakeEmail.com",
    "favoriteColor": "Pizza",
    "birthday": "02/29/1977"
    }      
###
PUT http://localhost:8080/contacts/6268b3327cbe1abba92df8a8/ HTTP/1.1 content-type: application/json

    # {
    # "firstName": "Regina A.K.A Phoebe",
    # "lastName": "Phalange A.K.A. Buffay",
    # "email": "realnameisphoebebuffay@FakeEmail.com",
    # "favoriteColor": "Rainbow",
    # "birthday": "02/29/1978"
    # }
    {
    "firstName": "Regina A.K.A Phoebe",
    "lastName": "Phalange A.K.A. Buffay",
    "email": "realnameisphoebebuffay@FakeEmail.com",
    "favoriteColor": "Rainbow",
    "birthday": "02/29/1978"
    }
###
DELETE http://localhost:8080/contacts/6276d10f1db3df5547eed5ec HTTP/1.1 content-type: application/json
###

//HEROKU
###
GET https://d-fry-cse341-api.herokuapp.com/contacts/
###
GET https://d-fry-cse341-api.herokuapp.com/contacts/6268b3327cbe1abba92df8a6
###
GET https://d-fry-cse341-api.herokuapp.com/contacts/6268b3327cbe1abba92df8a7
###
GET https://d-fry-cse341-api.herokuapp.com/contacts/6268b3327cbe1abba92df8a8
###
